spring:
  application:
    name: kronos-example-spring-boot-debug
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/sql_task_management"
    username: root
    password: rootroot
    dbcp2:
      max-idle: 10

server:
  port: 51801